name: 'build images'

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:22.19.0
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run test:cov