name: 'test'

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:22.19.0
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for GitVersion to work properly
      - run: npm install
      - run: npm run test:cov